--- 
- profile
- - general
  - - people
    - addresses
  - change_passwords
- catalogs
- - academicprogramtypes
  - acadvisittypes
  - activitygroups
  - articlestatuses
  - bookchaptertypes
  - booktypes
  - citizenmodalities
  - conferencescopes
  - conferencetypes
  - contracttypes
  - coursegrouptypes
  - degrees
  - editionstatuses
  - externaluserlevels
  - genericworkgroups
  - genericworkstatuses
  - groupmodalities
  - idtypes
  - indivadvicetargets
  - instadvicetargets
  - institutiontitles
  - institutiontypes
  - jobpositionlevels
  - jobpositiontypes
  - languagelevels
  - languages
  - mediatypes
  - migratorystatuses
  - modalities
  - prizetypes
  - projectstatuses
  - projecttypes
  - roleinbooks
  - roleinchapters
  - roleinconferences
  - roleinconferencetalks
  - roleincourses
  - roleinjobpositions
  - roleinjournals
  - roleinjuries
  - roleinprojects
  - roleinregularcourses
  - roleinseminaries
  - roleintheses
  - roleproceedings
  - seminarytypes
  - skilltypes
  - studentroles
  - talkacceptances
  - talktypes
  - techproductstatuses
  - techproducttypes
  - thesismodalities
  - thesisstatuses
  - titlemodalities
  - userroles
  - users
  - userstatuses
  - volumes